### ISSUE TITLE
Default, unused test directory causing issues in learn.co #staff

### ISSUE THREAD

**Issue by kevinmcalear** [learn-co-curriculum/fewpjs-stitching-together-the-three-pillars#3]
From my understanding, having this `test` directory makes learn think this is a lab. The default files the tests look for are `index.html` & `index.js`. There is no `index.js` and even if there was, these tests (and probably the full `test` directory) should be deleted.

**Comment by sgharms** [comment]
@kevinmcalear 

We need to trick learn into seeing this as a lab so that we get Learn IB IDE for free.

I think:

https://github.com/learn-co-curriculum/fewpjs-stitching-together-the-three-pillars/pull/4

Fixes? Please verify.

**Comment by ipc103** [comment]
Hey @sgharms  - seeing this as it appears, it's confusing from a student's perspective. @kevinmcalear - can we assume that if students see this as a lab, they'll know to fork/clone and run `learn` to get the green light?

**Comment by sgharms** [comment]
Assuming changes in #4 are integrated, we could add a "use `learn submit`" to move on to the README.

**Comment by ipc103** [comment]
Thanks @sgharms  - that sounds reasonable to me.

**Comment by sgharms** [comment]
@kevinmcalear has the next step on this one. If he agrees the PR is good,
I'll go forward with this plan.

>
