### ISSUE TITLE
Bug in code

### ISSUE THREAD

**Issue by micahshute** [learn-co-curriculum/fewpjs-stitching-together-the-three-pillars#7]
The event listener is attaching to `.like`, which includes the entire li. So, if the student clicks on the `Like! ` text rather than the heart, `undefined` is displayed because the text "Like! " is not in the glyphStates object. The easiest fix is to just change articleHearts to select all objects with the `like-glyph` class instead of the `like` class. This stops you from being able to click on the `Like! ` text, but it removes the bug. You would have to change the logic in the callback to keep the functionality of being able to click on the entire `li` and getting the correct response. will submit a pull request.

**Comment by sgharms** [comment]
Fixed by #8
